# Generated by Django 4.1.1 on 2022-09-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_alter_userprofile_managers_profilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
